### ISSUE TITLE
PDF Viewer is not merged properly on master

### ISSUE THREAD

**Issue by philipyoungg** [AcrossTheCloud/TBA21-client#264]
https://github.com/AcrossTheCloud/TBA21-client/pull/257

@matthewberryman looks like PDF viewer not merged properly on master. I can't see the change reflected on `ocean-archive.org`.

**Comment by matthewberryman** [comment]
Merged into staging in https://github.com/AcrossTheCloud/TBA21-client/pull/257
Pending client review before moving to master
