### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#297]
Two inter-related tasks:
1. In the item view (modal and page; both use same component ViewItem) add a button to the right of the share icon that copies the embed code as follows, using the FaFileCode icon `from 'react-icons/fa';`. There's a Share component in src/components/utils we have set up but this would need tweaking / copy and change for use. That same component is also used elsewhere (Profiles, Collections) that don't have embed versions so be careful not to break that.
```html
<iframe src="https://${window.location.hostname}/embed/${itemId}" title="itemTitle"/></iframe>
```
2. For the item editor and collection editor components, have the share (for collection) or share + embed (for items) near the top of the editor pane but only if the item / collection is published (`status===true`)

**Comment by philipyoungg** [comment]
Done
