### ISSUE TITLE
images wrong in intro pop up carousel

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#308]
Missing the search image:
![Screen Shot 2021-08-04 at 10 22 33 am](https://user-images.githubusercontent.com/2288238/128102665-fb14d148-f3ae-4cc2-bc97-fc5ad298719c.png)
Also missing the bubble loops.

**Comment by philipyoungg** [comment]
![CleanShot 2021-08-05 at 17 43 19@2x](https://user-images.githubusercontent.com/11477718/128337401-e2d29793-d8b5-473c-875a-1c08b167e1e4.jpg)

maybe the image has not loaded on your place? It's loaded on my end.

**Comment by matthewberryman** [comment]
Looks like you've renamed it from "05 texture.png" to "05 Texture.png" your end, but because you're on a case insensitive filesystem you hadn't added, committed and pushed, because in that case git won't pick up the change unless you explicitly use `git mv ...`

**Comment by philipyoungg** [comment]
Closing as it's already done
