### ISSUE TITLE
bubbles missing, masks the wrong sizes

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#309]
![Screen Shot 2021-08-04 at 10 23 03 am](https://user-images.githubusercontent.com/2288238/128102816-0228eebe-57d6-4fe4-b706-7b5fb05ab1b7.png)

**Comment by philipyoungg** [comment]
I think the sizes are based on provided svg. I'll look into if it's possible to manipulate the sizes to make it uniform.

**Comment by matthewberryman** [comment]
Sizes are better but bubbles (loops, from svgs) still missing.
<img width="1140" alt="Screen Shot 2021-08-09 at 4 42 56 pm" src="https://user-images.githubusercontent.com/2288238/128668634-f1bd3710-4574-4daa-a06a-5ab892c3eb24.png">

**Comment by philipyoungg** [comment]
Done

![CleanShot 2021-08-19 at 20 58 28@2x](https://user-images.githubusercontent.com/11477718/130081758-edaf0e2f-6378-4068-b8c5-c9d466070ffa.jpg)
