### ISSUE TITLE
intro carousel needs to be a separate component

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#310]
It's an intro to the whole of the OA, so I need to be able to reuse if the user hits the main page first, and also trigger it from a help menu item.

**Comment by matthewberryman** [comment]
@philipyoungg If you can refactor this out, and drop the component back in to the stories page, I can do the rest (menu + OA main page). Perhaps this will also help with https://github.com/AcrossTheCloud/TBA21-client/issues/311

**Comment by philipyoungg** [comment]
How do I trigger the ask for cookies?

**Comment by philipyoungg** [comment]
Closing as it's already done
