### ISSUE TITLE
closing cookie acceptance modal also closes the intro carousel modal

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#311]
These should be independent

**Comment by philipyoungg** [comment]
Interesting. It should be independent. Probably related to z index issue.

**Comment by matthewberryman** [comment]
For reference, cookie acceptance modal is triggered if isPrivacyPolicyAccepted_16092019 cookie is present and `true`, so you can delete just that cookie / use incognito mode to ensure it's clear.

**Comment by philipyoungg** [comment]
Would it make sense to trigger the story onboarding popup after the privacy policy is accepted/rejected?

**Comment by matthewberryman** [comment]
Yes, please do it that way.

**Comment by philipyoungg** [comment]
Done
