### ISSUE TITLE
star and circle not vertically aligned

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#312]
![Screen Shot 2021-08-04 at 10 39 47 am](https://user-images.githubusercontent.com/2288238/128103743-76b2e535-ba82-4a16-bc3f-40cd285b83f6.png)

**Comment by matthewberryman** [comment]
I've tested this one and not been able to reproduce in Safari, Chrome and on mobile iOS and Chrome for Android.

**Comment by philipyoungg** [comment]
Thanks for the help, will test cross browser for this.

**Comment by philipyoungg** [comment]
Closing as it's already done
