### ISSUE TITLE
fonts still need some work

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#313]
![Screen Shot 2021-08-04 at 10 51 54 am](https://user-images.githubusercontent.com/2288238/128104642-95a2c5fd-7425-4904-9d90-cd089afb103d.png)

**Comment by philipyoungg** [comment]
Ah, thanks for the clarification. So the small text is the title. I thought the ocean labor part is the category, which you told me is not needed (as the one on breadcrumb)

**Comment by philipyoungg** [comment]
Closing as it's already done
