### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#314]
Per figma design, we only want one style of header displayed irrespective of header tag level `<h1>`...`<h6>` so can you please style all of them the same to match design.
[Example of issue](https://staging.ocean-archive.org/story/headlines-testing)

**Comment by philipyoungg** [comment]
Sure thing, unfortunately I can't deduce that based on the figma file alone.

**Comment by matthewberryman** [comment]
You just need to style h2...h6 the same as you've got for h1.

**Comment by philipyoungg** [comment]
I added `8rem` margin bottom as separator between section. Let me know if we don't need it.

![CleanShot 2021-08-05 at 17 54 59@2x](https://user-images.githubusercontent.com/11477718/128338902-c9319173-e977-4069-a6c1-99af442a8a1d.jpg)

**Comment by matthewberryman** [comment]
Thanks. I'll check the separator addition with the client tomorrow, just focus on h css for now.

**Comment by philipyoungg** [comment]
Closing as it's already done
