### ISSUE TITLE
Count wrong

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#317]
"Displaying _x_ out of _n_ stories" > here _n_ should be total number of stories in the system as a whole.

**Comment by matthewberryman** [comment]
I checked and this value can come from the headers 
https://wordpress.stackexchange.com/questions/217490/get-post-count-in-wp-rest-api-v2-and-get-all-categories

**Comment by philipyoungg** [comment]
I did use X-WP-Total.

How do you came up with conclusion that the count is wrong? Perhaps there's a bug somewhere else.

![CleanShot 2021-08-05 at 17 24 50@2x](https://user-images.githubusercontent.com/11477718/128335036-31998b21-57c6-46f2-b46b-821ec9dcfea7.jpg)

**Comment by philipyoungg** [comment]
Proof that it's the correct number.

![CleanShot 2021-08-05 at 17 31 42@2x](https://user-images.githubusercontent.com/11477718/128335888-40e81ed4-2d4b-453a-9f1e-5c6f0bc63399.jpg)

**Comment by matthewberryman** [comment]
It breaks when you add a filter.  It seems you need to make two calls, one without the query params in order to get the total in the system, the other one to get matching stories (the headers on this only give the total matching)
<img width="1168" alt="Screen Shot 2021-08-05 at 8 32 39 pm" src="https://user-images.githubusercontent.com/2288238/128336139-368487a0-d179-4181-8f05-a3156b44b5da.png">

**Comment by philipyoungg** [comment]
Ah I see what you meant. 

Isn't the current behavior is technically correct though? 

Say there's 30 items that matches the filter, the current UI shows 10 items. It's accurate in the sense that it's "10 out of 30" instead of "10 out of n articles without filter"—which actually is misleading.

**Comment by matthewberryman** [comment]
No , it's a different meaning of "out of". They want the number of stories that match "out of" total stories.

**Comment by philipyoungg** [comment]
OK cool. Not gonna lie, it's confusing UI-wise. 

- Imagine the copy shows "12 out of 340 stories" 
- 12 posts are shown (10 + 2 after infinite scroll).
- but the UI shows that there's "no more story to show" at the end of the posts.

**Comment by matthewberryman** [comment]
The language at end should be changed to "no more matching stories to show" to be clear on that. The intent is to show the number of total stories always.

**Comment by philipyoungg** [comment]
Closing as it's already done
