### ISSUE TITLE
colour theme (night / day / gradient, auto) should also apply to main stories page

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#318]
Also must include the switcher there

**Comment by philipyoungg** [comment]
Need figma design

**Comment by matthewberryman** [comment]
Same colour theme as in figma for stories.

**Comment by philipyoungg** [comment]
Sorry, I meant the UI for the theme selector. Or it's OK to just show it on the story view page?

**Comment by matthewberryman** [comment]
Ah, gotcha. Yeah it needs to be there on stories page too but I will check.

**Comment by philipyoungg** [comment]
Closing as it's already done. Please open a new issue for the toggler.
