### ISSUE TITLE
placement of highlights wrong on mobile

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#320]
Sorry, one more thing we noticed:
On mobile, only the first highlight is visible, so it's not clear that swiping sideways would reveal more:
<img width="404" alt="Screen Shot 2021-08-09 at 4 44 21 pm" src="https://user-images.githubusercontent.com/2288238/128668802-a5620177-037e-4549-bb44-46c7825cac04.png">

If you bring these over to the left a bit it's much clearer:
<img width="395" alt="Screen Shot 2021-08-09 at 4 44 33 pm" src="https://user-images.githubusercontent.com/2288238/128668859-480c7143-6993-4ea4-9d69-c803c68d1fa8.png">

**Comment by philipyoungg** [comment]
Done. It's now responsive based on device width.
