### ISSUE TITLE
article type used incorrectly

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#322]
Article type is hard coded to "Essay". This needs to be set to the appropriate type, and that type should also not appear in the list of concept tags (categories).
<img width="999" alt="Screen Shot 2021-08-16 at 9 13 10 am" src="https://user-images.githubusercontent.com/2288238/129495504-019102ae-721c-43df-b3ae-801778e33fa3.png">

**Comment by matthewberryman** [comment]
Just noting there are a couple of other tweaks on the line where the type should be displayed in the list of stories I have pushed to pyg/stories branch, so be sure to `git pull` first to avoid merge conflicts.

**Comment by philipyoungg** [comment]
There isn't filter by Essay right?

**Comment by matthewberryman** [comment]
The type you had already programmed in as a filter. It includes Essay but other ones as shown in screenie with parent "type".
StoryItem.tsx L57 you'd hardcoded Essay in. This needs to show the type.
L61 and L62 of same file also need some work. L61 says "Concept tags" but these are only the categories with "concept tags" as parent, so you will need to add a filter.

**Comment by philipyoungg** [comment]
Done
