### ISSUE TITLE
disqus not visible on stories

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#323]

**Comment by philipyoungg** [comment]
in story page? What are the decision? Are we going to embed it? If yes, what's the ID?

**Comment by matthewberryman** [comment]
Put it at the bottom of the story. Staging is already configured as a site in disqus, so for https://help.disqus.com/en/articles/1717112-universal-embed-code set url=story url as hosted on staging and id=work story id (number, not slug)

**Comment by philipyoungg** [comment]
done
