### ISSUE TITLE
"~ DIVE INTO STORIES" not sticky on desktop

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#326]
should behave the same as on mobile

**Comment by philipyoungg** [comment]
![CleanShot 2021-08-22 at 16 24 33@2x](https://user-images.githubusercontent.com/11477718/130349824-34b007f3-1a09-4488-88aa-e1351e266087.jpg)

what functionality did it introduce for the stickness?

**Comment by matthewberryman** [comment]
The "~DIVE INTO STORIES" needs to be sticky on both.

**Comment by philipyoungg** [comment]
It's done. It's really weird though as it serves no functionality and reduce vertical space.
