### ISSUE TITLE
UI alignment wrong

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#327]
* "~ DIVE INTO DESIGN" needs to be brought to the left.
* vertical alignment of first story title should match "Displaying x of ..."

design:
<img width="1023" alt="Screen Shot 2021-08-22 at 9 57 56 am" src="https://user-images.githubusercontent.com/2288238/130337715-8317e0fe-456d-4c0a-b1ed-8e5ec06bc603.png">

currently:
<img width="1182" alt="Screen Shot 2021-08-22 at 9 58 14 am" src="https://user-images.githubusercontent.com/2288238/130337711-f3a8c43c-ed55-424b-9c1d-71ffa5e97476.png">

**Comment by matthewberryman** [comment]
2nd bullet point not done

**Comment by philipyoungg** [comment]
Done. It's now aligned.
