### ISSUE TITLE
transition to mobile / narrow view wrong

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#329]
Should happen before the filter text overflows the boxes:
<img width="770" alt="Screen Shot 2021-08-22 at 10 07 18 am" src="https://user-images.githubusercontent.com/2288238/130337821-777ea8c9-5164-40de-99c1-b4bb4430866a.png">

**Comment by philipyoungg** [comment]
I hide the overflow instead. If we change the mobile breakdown dimension, it'll trickle down to other components.

**Comment by philipyoungg** [comment]
![CleanShot 2021-08-22 at 16 30 39@2x](https://user-images.githubusercontent.com/11477718/130350118-24b9c413-128e-4809-94fc-41a90e508e45.jpg)
