### ISSUE TITLE
rainbow bar

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#331]
The rainbow bar (same as on homepage) should also be on single story view, between menu and the rest of the page.

<img width="750" alt="Screen Shot 2021-08-22 at 10 02 47 am" src="https://user-images.githubusercontent.com/2288238/130341790-5bfef52f-9420-468f-bf70-1bd8c058650e.png">

**Comment by philipyoungg** [comment]
Proven to be painful to work on
