### ISSUE TITLE
story text on hover needs to match design

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#333]
<img width="1473" alt="Screen Shot 2021-08-24 at 1 30 41 pm" src="https://user-images.githubusercontent.com/2288238/130551455-95bb57e5-9e01-46e3-8e49-b4d8b9379a71.png">

**Comment by matthewberryman** [comment]
I've added the functionality in above commit in story_excerpt_on_hover branch since the hover action wasn't captured in figma, however the width of the text box plus the font size will need some tweaking to match what was in figma. I had a quick try but there's a lot of css styles flying all over the place and I'm short on time this week on other projects.

**Comment by philipyoungg** [comment]
Done on `pyg/stories`
