### ISSUE TITLE
clicking a menu item should close burger bar on mobile

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#336]

**Comment by matthewberryman** [comment]
* Logging in throws an error:
<img width="748" alt="Screen Shot 2021-08-30 at 10 37 00 am" src="https://user-images.githubusercontent.com/2288238/131270877-c87863e4-bc83-4e84-87d5-c446ca3bcf7b.png">
* Submenu items (e.g. About > Guide ) only close the submenu; we need the whole burger menu to close.

**Comment by matthewberryman** [comment]
[The bug](https://www.dropbox.com/s/u8wxg1q8zodck7x/Screen%20Recording%202021-09-07%20at%207.18.06%20am.mp4?dl=0) is still there in https://github.com/AcrossTheCloud/TBA21-client/commit/3009a5c3a0b30c2b3314353ecdef0cc808d0ae81. 

If you look at the way the JSX.Elements are set out, because these are at the same level as the definition of NavLinkClose, they are run asynchronously with the decoration of the Header object with the NavLinkClose function, so when you get to this line
https://github.com/AcrossTheCloud/TBA21-client/blob/361785fdcfc36a0fd184297645be9d5e85739975/src/components/layout/Header.tsx#L130 
the `this.NavLinkClose` may be undefined. This consistently crops up for me on login (starting from the logged out state) but sometimes on other occasions since it's a timing-sensitive bug. 

I also note that if I start in the narrow/mobile view of the page, I cannot click on the login button (per screen recording).

**Comment by matthewberryman** [comment]
Close, but not quite. I've pulled all of the commits, but in mobile view, clicking login closes the menu instead of taking the user to the login screen.

**Comment by philipyoungg** [comment]
Closing as you said it's resolved on last chat from Whatsapp
