### ISSUE TITLE
dropdown menu for sections

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#337]

**Comment by matthewberryman** [comment]
Scroll bars in the breadcrumb dropdown are gone on macOS but are still present on Windows - possible to remove them?

**Comment by philipyoungg** [comment]
Not possible. It's OS level. If you use external mouse (not touchpad) the scroll bar will also show on Mac.

**Comment by matthewberryman** [comment]
You can hide scrollbars / set width to 0.

https://www.w3schools.com/howto/howto_css_hide_scrollbars.asp

I’ve tested something similar on Windows before.

Can’t autohide that is true but can hide.

On 7 Sep 2021, at 17:13, Philip Young ***@***.***> wrote:

﻿

Not possible. It's OS level. If you use external mouse (not touchpad) the scroll bar will also show on Mac.
