### ISSUE TITLE
narrow desktop / mobile stories search

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#339]
At minimum: Align the top of the search section with the colour gradient strip, so the stories list text can't be seen in that spot. I can reproduce in narrow desktop view on Chrome & Firefox, and Android. Not an issue on iOS, but please double check.
Ideally also: if you can prevent scrolling of the stories list while the mouse / touch location is scrolling in the search space, then do that, if it's too hard then don't worry.

<img width="858" alt="Screen Shot 2021-09-02 at 7 33 52 pm" src="https://user-images.githubusercontent.com/2288238/131821941-eb191f65-b83d-4eda-9146-d8f3396adbdf.png">

**Comment by matthewberryman** [comment]
Can't scroll on the search area any more.

**Comment by philipyoungg** [comment]
@matthewberryman I can scroll just fine on my real iOS device. Can you try again?

**Comment by matthewberryman** [comment]
Sorry, I must have been on the wrong commit. I tried in iOS and in Android and narrow desktop.

**Comment by matthewberryman** [comment]
@philipyoungg if you hit mobile view in desktop browser > select iPhone 5 then you can see an issue we're having on small mobile devices where the user cannot scroll to apply in order to apply the search.
<img width="502" alt="Screen Shot 2021-09-13 at 5 15 40 pm" src="https://user-images.githubusercontent.com/2288238/133040063-11158cbd-8a41-44a6-bf9d-45cb1bc41888.png">

**Comment by matthewberryman** [comment]
I made a fix that also brings it up a bit, however the problem still remains - especially once you start adding tags/regions etc.
