### ISSUE TITLE
Search from concept/keyword tags on single story view

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#340]
* Only on single story view.
* No search bar visible by default.
* Default is not to have the search bar at all, but to open it, and show search results for that tag, if user clicks on a tag. 
* I guess we can get users to use tags we define (as long as we can style them, and make them as links that trigger a search for the value) eg `<concept_tag>atmospheric phenomenon</concept_tag>`. Keyword tag similar with `<keyword_tag>A keyword</keyword_tag>`. 
* Concept tags have a # in front and box (check on figma and current OA prod site).

**Comment by matthewberryman** [comment]
Great work, but styling is a bit off. Concept tags should have boxes around them, and not bold:
<img width="602" alt="Screen Shot 2021-09-08 at 10 00 00 pm" src="https://user-images.githubusercontent.com/2288238/132505498-fe1fe0d1-bcf0-4c7d-950d-700afc1886a9.png">

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-08 at 19 11 56@2x](https://user-images.githubusercontent.com/11477718/132507030-4c494e83-aa73-4582-8726-81ef564a318d.jpg)
![CleanShot 2021-09-08 at 19 11 53@2x](https://user-images.githubusercontent.com/11477718/132507031-8c9bce49-4e81-4c36-8ae8-69547900386b.jpg)

**Comment by matthewberryman** [comment]
concept tags: boxes are too big.
keyword tags: should be styled how you had them originally.
