### ISSUE TITLE
Quote styling

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#343]
In quotation marks, same size font,  italics, aligned to the centre, cca 70% of the width of the rest of the text
Name (citation) under the quote: not italics, en dash before the name, aligned to the right.
<img width="607" alt="Screen Shot 2021-09-07 at 10 00 20 am" src="https://user-images.githubusercontent.com/2288238/132267376-23958feb-1c69-4b06-80b2-af1ea92f2e7e.png">

There's a quote I added to the Wollongong whales story to test on.

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-08 at 13 04 01@2x](https://user-images.githubusercontent.com/11477718/132455001-3a0c82bf-60b4-4b6f-9bfa-bcbea12d8039.jpg)

No italic font so it's bolded even though `font-style: italic`

**Comment by matthewberryman** [comment]
Ah I guess that explains https://github.com/AcrossTheCloud/TBA21-client/issues/356 too. I will try and chase down an italics font.

**Comment by matthewberryman** [comment]
See https://github.com/AcrossTheCloud/TBA21-client/issues/356#issuecomment-914954299 regarding italics. Please ensure that it works for quotes too, also I can't yet see a push for this work? Please close once it's tested and pushed.
