### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#344]
Refer to figma for desktop and mobile design

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-10 at 15 03 09@2x](https://user-images.githubusercontent.com/11477718/132821127-05931e94-0c9e-436b-afb2-d1ac32f6c400.jpg)
![CleanShot 2021-09-10 at 15 03 18@2x](https://user-images.githubusercontent.com/11477718/132821136-e880d4b3-f2f7-48bb-9fd0-19f158fc7b3e.jpg)
