### ISSUE TITLE
main search (from search bar) needs to include stories

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#348]
picture on the right, story title on right, same look and feel. Need to merge the two lists from the two APIs based on creation time to show in order of time from most recent to last (let me know if I need to change default ordering on TBA21-API, I will investigate a little tomorrow
<img width="2146" alt="Screen Shot 2021-09-07 at 5 03 19 pm" src="https://user-images.githubusercontent.com/2288238/132299361-556c7a49-e3f6-4863-99a0-10ae8d2672f3.png">

**Comment by philipyoungg** [comment]
Fetching first 50 items

**Comment by matthewberryman** [comment]
Need to include search from text. Metadata field needs to show on the right side (keep to existing ones e.g. "Title" with that capitalisation, except for story contents show "Story content")
<img width="1275" alt="Screen Shot 2021-09-08 at 10 12 57 pm" src="https://user-images.githubusercontent.com/2288238/132507168-628271cb-d4f0-404e-b971-650b444f67ad.png">

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-08 at 19 30 12@2x](https://user-images.githubusercontent.com/11477718/132509539-ce805352-62c7-4c63-9cf0-6820ce4e6dfc.jpg)

Added free text search on story

**Comment by matthewberryman** [comment]
selecting an item doesn't close the search results modal, meaning you can't see the item model

**Comment by matthewberryman** [comment]
@philipyoungg there are some other things I would like @mehrdadgit to work on. Can you please fix this asap. I am happy if the search results stay there, just that the item modal needs to lift up so I can see it. To trigger, select a story -> concept tag (that has other non-story items) -> click non-story item.

**Comment by philipyoungg** [comment]
Which item modal? The old one? (Not stories)?

**Comment by matthewberryman** [comment]
The item modal (for items that aren't stories) should be above the search modal. Just a z-index issue I believe. See bug here:
https://user-images.githubusercontent.com/2288238/132802321-df8a995c-1961-489b-b085-6872c6718d63.mp4
