### ISSUE TITLE
multiple authors from category

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#351]
Show one or more authors based on category (subcategory of authors), not post author. Display and functionality to remain the same.

**Comment by philipyoungg** [comment]
Can you give me more info? Multiple author on filter, multiple author to show on individual post, etc

It's not clear.

**Comment by matthewberryman** [comment]
Filter: search on single authors (for stories that they are an author or co-author).
Multiple authors display: comma separated list, same styling as we have now.

**Comment by matthewberryman** [comment]
Remove leading comma and space:
<img width="267" alt="Screen Shot 2021-09-08 at 4 13 25 pm" src="https://user-images.githubusercontent.com/2288238/132455979-0a8d663a-afb7-4542-b7f8-3bd59d759c34.png">

**Comment by matthewberryman** [comment]
Please don't include the Wordpress author, per original comment. Just the ones from categories

**Comment by matthewberryman** [comment]
I've removed the stray comma, however search needs some work (both search and the filter):
<img width="937" alt="Screen Shot 2021-09-08 at 7 03 09 pm" src="https://user-images.githubusercontent.com/2288238/132480122-d541539f-0001-4be4-88e1-4f40aa72e062.png">

**Comment by matthewberryman** [comment]
@philipyoungg 
https://github.com/AcrossTheCloud/TBA21-client/commit/808492655ee2b7952e9bc6e0c918dfd3af21c778 : removes the filter on wordpress author, leaving the other one using only categories, and https://github.com/AcrossTheCloud/TBA21-client/commit/988ea2084d032e9851dacee937a21ab33b881d94 fixes the grammar.
https://github.com/AcrossTheCloud/TBA21-client/commit/7c58627f1f6e0bca8509c5b95ca21eb11f8db96d removes the wordpress author from display and does comma correctly.

The remaining issue is that the freetext search doesn't find articles by author.

**Comment by matthewberryman** [comment]
Line wrapping should be at list of authors level not for individual authors on mobile.

**Comment by matthewberryman** [comment]
Also, authors need to be displayed in the highlights (see Figma design)

**Comment by matthewberryman** [comment]
@philipyoungg when putting in authors, please put in with `text-align: centre;`

**Comment by philipyoungg** [comment]
> that the freetext search doesn't find articles by author (categories, no longer using wordpress author).

What I did:
- get categories
- search categories that includes the title
- add the category ID API call
- also add text to the API call

Wordpress API is and. If I search "Katar" (intention: for Katarina), category found it, but the article didn't have the word "Katar" so it's filtered out.

The only alternative is to have 2 separate API call and join it. But that adds tons of complexity—especially the logic on infinite scroll.

```
let categories: WP_REST_API_Terms = Object.values(categoryById);
    let categoryIdsThatMatchTitle = new Set(
      categories
        .filter((c) => c.name.toLowerCase().includes(title.toLowerCase()))
        .map((c) => c.id)
    );

    let allCategoryIds = new Set(
      Array.from(categoryIdsThatMatchTitle).concat(
        Array.from(selectedCategoryIds)
      )
    );

    console.log({ categories, categoryIdsThatMatchTitle, allCategoryIds });

```

**Comment by philipyoungg** [comment]
It's done without the free text
