### ISSUE TITLE
Audio player when embedded

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#353]
At the moment, the user has to click on waveform to bring up the player. When the audio file is embedded (and only when embedded) we would like to have it visible always. 

Notes:
* Please work in the audio_when_embedded branch and submit a PR with squash commit against master branch when done.
* If you use `ENV=prod npm run start` it will point you against the prod environment so that the [test example](https://github.com/AcrossTheCloud/TBA21-client/blob/audio_when_embedded/test.html) works. Once done, please remove that test.html file before submitting the PR.
* I tried a quick hack in https://github.com/AcrossTheCloud/TBA21-client/blob/audio_when_embedded/src/components/layout/audio/AudioPreview.tsx (see comments in the file) but it didn't work :/

**Comment by mehrdadgit** [comment]
Done.
