### ISSUE TITLE
italics rendered wrong

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#356]
<img width="606" alt="Screen Shot 2021-09-08 at 2 02 38 pm" src="https://user-images.githubusercontent.com/2288238/132444563-2189595a-22c7-4763-824d-c4a6dd754466.png">

**Comment by matthewberryman** [comment]
@philipyoungg I found that I had Minion Pro It(alic) in the codebase, however I had mangled the scss when describing it, in that the `font-style: italic;` pointed to bold and similarly for `font-style: bold;`, now fixed in https://github.com/AcrossTheCloud/TBA21-client/commit/afef079d2ec5ff1b6cfe09824272a3e2578b3cca 
However you will need to style the `<em>`s appropriately for this.

**Comment by philipyoungg** [comment]
Im not sure I understand. 

So I need to put every italics inside <em> tag?

Is it possible to just put it on css with font style italics instead? 

That's going to be a lot of work with jquery...

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-08 at 13 34 17@2x](https://user-images.githubusercontent.com/11477718/132458348-f2aae023-4bcb-446b-841a-99557116c601.jpg)

Nevermind, it works now!

**Comment by matthewberryman** [comment]
I can't see it yet (just pulled) in either quotes or for `<em>`s in the stories. I am not talking about changing the tags just ensuring with css that the font-style is italic for `<em>`s
