### ISSUE TITLE
footnotes

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#359]
Client has changed mind on footnotes (!) and wants to use the Modern Footnotes plugin instead. So, rip out the existing work. We need to match the functionality and styling (except for font). Example in section A of Wollongong Whales story.

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-10 at 20 33 33](https://user-images.githubusercontent.com/11477718/132861499-7b3231a1-d8cd-40c2-80d1-1a43d02dad6e.gif)
