### ISSUE TITLE
when adding chapter strip on end of breadcrumb trail - remove flicker and make sure everything is vertically aligned

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#365]
e.g. Wollongong Whales story

**Comment by philipyoungg** [comment]
![CleanShot 2021-09-10 at 19 59 43@2x](https://user-images.githubusercontent.com/11477718/132856968-1f0ad744-6a38-40b9-9498-81cc7a9a0040.jpg)
