### ISSUE TITLE
burger menu on small sizes

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#373]
For `@media screen and (max-width: 768px)` collapse top right icons for share/favourite/colour-toggler into a menu bar (screenshot shows expanded view).
<img width="293" alt="Screen Shot 2021-09-14 at 12 07 16 pm" src="https://user-images.githubusercontent.com/2288238/133182759-d4022822-8d5a-44b9-836a-f3e0988a7baa.png">

**Comment by matthewberryman** [comment]
needs further (urgent) work - it needs to open to the right of the three dots as shown in original comment, not below

**Comment by mehrdadgit** [comment]
Done
