### ISSUE TITLE
Favourite stories display wrong when stories is absent from favourites, or empty list

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#380]
If profile favourites is missing the `stories` key, or if `"stories": []`, then all stories are shown as favourites, instead of no stories. Also, in the case that no stories are favourited, the section header "Favourite Stories" should be absent, incl. the reactstrap Row (which would otherwise take up space if empty).

**Comment by philipyoungg** [comment]
Done
